[package]
name = "dragonglass-core"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
nalgebra-glm = "0.7.0"
winit = "0.21"
legion = "0.2.1"
