[package]
name = "dragonglass-backend-vulkan"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
winit = "0.22.1"
ash = "0.29.0"
env_logger = "0.7.1"
log = "0.4.8"
nalgebra = "0.19.0"
nalgebra-glm = "0.5.0"
snafu = "0.6.0"
image = "0.23.3"
petgraph = "0.5.0"
legion = "0.2.1"
gltf = "0.14.0"
vk-mem = "0.2.0"
glob = "0.3.0"
raw-window-handle = "0.3.3"
dragonglass-core = { path = "../../../core", version = "0.1.0" }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.8", features = ["windef", "libloaderapi"] }
